export const ADMIN_AUTH_CONFIG = Symbol('ADMIN_AUTH_CONFIG');
export const ADMIN_PERMISSION_METADATA = Symbol('ADMIN_PERMISSION_METADATA');
export const ADMIN_MFA_METADATA = Symbol('ADMIN_MFA_METADATA');
